backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'writers'
    label: 'Writers'
    folder: 'src/pages/writers'
    create: true
    slug: '{{fullName}}'
    identifier_field: fullName
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'writer' }
      - { label: 'Page Address', name: 'page', widget: 'string' }
      - label: 'Language'
        name: 'language'
        widget: 'select'
        options:
          - { label: 'English', value: 'en' }
          - { label: 'Русский', value: 'ru' }
          - { label: 'Беларускi', value: 'by' }
      - { label: 'Full Name', name: 'fullName', widget: 'string' }
      - { label: 'Birth Date', name: 'birthDate', widget: 'date' }
      - { label: 'Death Date', name: 'deathDate', widget: 'date' }
      - { label: 'Place of Birth', name: 'placeOfBirth', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - label: 'Timeline'
        name: 'timeline'
        widget: 'list'
        fields:
          - { label: 'Date', name: 'date', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
      - label: 'Works'
        name: 'works'
        widget: 'list'
        fields:
          - { label: 'Date', name: 'date', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Gallery'
        name: 'gallery'
        widget: 'list'
        fields:
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Alt', name: 'alt', widget: 'string' }
      - label: 'Video'
        name: 'video'
        widget: 'list'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Video URL', name: 'videoURL', widget: 'string' }
      - label: 'Map'
        name: 'map'
        widget: 'list'
        fields:
          - {
              label: 'Latitude',
              name: 'lat',
              widget: 'number',
              valueType: 'float',
            }
          - {
              label: 'Longitude',
              name: 'lon',
              widget: 'number',
              valueType: 'float',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
  - name: 'workLog'
    label: "Work Log"
    folder: 'src/pages/workLogs'
    create: true
    slug: '{{fullName}}'
    identifier_field: fullName
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'workLog' }
      - { label: 'Developer Name', name: 'devName', widget: 'string' }
      - { label: 'Github Account Link', name: 'github', widget: 'string' }
      - label: 'Task List'
        name: 'taskList'
        widget: 'list'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hours', name: 'hours', widget: 'number' }